
Based and credit to DSelders's repo.

== Installation:

	git clone https://github.com/itlinux/vimrc ~/.vim

Get prerequisites:

=== For Mac

:NOTE: IMPORTANT the YouCompleteMe package needs extra steps to get installed.
In linux you need to have vim 8 version otherwise it will not work. 

.. Installing needs cmake (use brew)
.. python still using brew or mkvirtualenv
.. once package is installed go inside the YouCompleteMe which using the minpac 
    is located in the ~/.vim/pack/minpac/start/YouCompleteMe and run the install.py
    script. I had an issue where it was not building the "cregex" so the easier way 
    was make sure you have all the dependency and remove the folder YouCompleteMe 
    once that rerun the PackUpdate command and reinstall it. Then process the installation 
    again with the install.py. At that point all worked. 

----
cd ~/.vim
git clone https://github.com/k-takata/minpac.git ./pack/minpac/opt/minpac
pip install -r requirements.txt
----

=== For Linux

----
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
pip install -r requirements.txt
----

==  Create symlink:

=== For Mac

----
ln -s ~/.vim/vimrc-mac ~/.vimrc
---- 

=== For Linux (CentOS7)

----
ln -s ~/.vim/vimrc-linux ~/.vimrc
----

=== Install Asciidoctor:


==== For Mac

----
brew install asciidoctor
or
port install asciidoctor
----

==== For Linux CentOS 7

enabled epel 
----
yum install rubygem-asciidoctor.noarch
----



==  Install plugins

=== For Mac

----
vim
:PackUpdate
----

=== For Linux

----
vim
:PluginUpdate
----
==== Repo for VIM 8 CentOS 7
----
[lbiaggi-vim80-ligatures]
name=Copr repo for vim80-ligatures owned by lbiaggi
baseurl=https://copr-be.cloud.fedoraproject.org/results/lbiaggi/vim80-ligatures/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/lbiaggi/vim80-ligatures/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
----

----
yum install cmake 
cd ~/.vim/bundle/YouCompleteMe
/install.py --clang-completer
----

=== Undo

----
Folders Needed:
mkdir ~/.vim/.undo/
----
